### ISSUE TITLE
Trying to import FASTA into source

### ISSUE THREAD

**Issue by tristanpwdennis** [giffordlabcvr/gluetools#5] opened 2016-03-23 11:21 UTC
Exception in thread "main" org.apache.cayenne.validation.ValidationException: [v.3.1 Sep 20 2014 14:06:21] Validation failures: Validation failure for uk.ac.gla.cvr.gluetools.core.datamodel.seqOrigData.SeqOrigData.packedData: "packedData"  is required.
Validation failure for uk.ac.gla.cvr.gluetools.core.datamodel.seqOrigData.SeqOrigData.packedData: "packedData"  is required.
    at org.apache.cayenne.access.ObjectStoreGraphDiff.validateAndCheckNoop(ObjectStoreGraphDiff.java:111)
    at org.apache.cayenne.access.DataContext.flushToParent(DataContext.java:806)
    at org.apache.cayenne.access.DataContext.commitChanges(DataContext.java:756)
    at uk.ac.gla.cvr.gluetools.core.command.CommandContext.commit(CommandContext.java:137)
    at uk.ac.gla.cvr.gluetools.core.command.project.ImportSequenceCommand.execute(ImportSequenceCommand.java:59)
    at uk.ac.gla.cvr.gluetools.core.command.project.ImportSequenceCommand.execute(ImportSequenceCommand.java:20)
    at uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:176)
    at uk.ac.gla.cvr.gluetools.core.console.Console.executeTokenStrings(Console.java:127)
    at uk.ac.gla.cvr.gluetools.core.console.Console.handleLine(Console.java:117)
    at uk.ac.gla.cvr.gluetools.core.console.Console.handleInteractiveLine(Console.java:91)
    at uk.ac.gla.cvr.gluetools.core.console.Console.interactiveSession(Console.java:378)
    at uk.ac.gla.cvr.gluetools.core.console.Console.main(Console.java:296)

**Comment by joshsinger** [comment] 2016-03-23 14:43
duplicate of this: https://github.com/giffordlabcvr/gluetools/issues/2

**Closed as completed** 2023-11-22 05:53 UTC
Labels: duplicate
